server:
  port: 89

spring:
  application:
    name: cloud-order-server
    #服务追踪
    zipkin:
      base-url: http://59.110.171.189:9411/ # zipkin服务器的地址
      discovery-client-enabled: false    #关闭服务发现，否则spring cloud会把zipkin的url当作服务名称
      sender:
        type: web #设苦使用http的方式传输数据
    sleuth:
      traceId128: true
      sampler:
        probability: 1.0 #抽样采集率为100%,默认为0.1 ，即10%
      propagation-keys: user_name
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true   # 从eureka注册中心获取服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
