### consul服务端口号
server:
  port: 81

spring:
  application:
    name: cloud-consumer-order
  ###consul服务注册中心
  cloud:
    consul:
      host: 59.110.171.189
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
