server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coder-fang/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
          username: coder-fang
          password: Lf2673563903,
          default-label: master
          skip-ssl-validation: true
      ####读取分支
      label: master
#  rabbitmq:
#    host: 59.110.117.189
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
